export PATH=$HOME/bin:$PATH
export AWS_DEV_ENVIRONMENT=true
export ERL_AFLAGS="-kernel shell_history enabled"

source <(curl -sL https://raw.githubusercontent.com/nulib/aws-developer-environment/main/individual/support/dev_environment.sh)
source <(curl -sL https://raw.githubusercontent.com/nulib/aws-developer-environment/main/individual/support/asdf-helpers)

. $HOME/.asdf/asdf.sh
if [[ -e ~/.aws/credentials ]]; then
  rm -f ~/.aws/credentials
fi
if [[ -d ~/environment/miscellany ]]; then 
  source ~/environment/miscellany/secrets/dev_environment.sh;
fi
